import React, {useEffect, useRef, useState} from 'react';
import {ArrowLeft, Camera as CameraIcon, Play} from 'lucide-react';
import {createRoot} from 'react-dom/client';
import content from './content/content.json';
import './styles.css';

const petals = ['🌷','🌷','🌸','🌷','🌹','🌷','🌸'];

function SparkleField({active=true}) { return active && <div className="sparkles" aria-hidden>{Array.from({length:18},(_,i)=><i key={i} style={{'--i':i,'--x':`${(i*37)%96+2}%`,'--y':`${(i*53)%90+5}%`}}>✦</i>)}</div> }
function Envelope({small=false, onClick}) { return <button className={`envelope ${small?'small':''}`} onClick={onClick} aria-label="Open letters"><span className="env-fold"/><span className="heart-seal">♥</span></button> }
function Bouquet({onClick, hero=false}) { return <button className={`bouquet ${hero?'hero':''}`} onClick={onClick} aria-label="Open cat flowers"><span className="stems"/>{petals.map((p,i)=><span className="flower" key={i} style={{'--i':i,'--row':i%3}}>{p}</span>)}<span className="paper-wrap"/><span className="bow">🎀</span></button> }
function CameraObject({onClick}) { return <button className="camera-object" onClick={onClick} aria-label="Open memories"><span className="camera-top"/><span className="camera-lens"><i/></span><span className="camera-shine"/></button> }
function MiniCake({onClick, flames=true, smoke=false, cut=false, slice=false}) { return <button className={`mini-cake ${cut?'cut':''} ${slice?'slice':''}`} onClick={onClick} aria-label="Open cake experience"><span className="cake-number">21</span><span className="candles">{Array.from({length:9},(_,i)=><i key={i} style={{'--i':i}}>{flames&&<b/>}{smoke&&<em>〰</em>}</i>)}</span><span className="cake-top"/><span className="cake-body">{Array.from({length:5},(_,i)=><b key={i}>♥</b>)}</span><span className="cake-plate"/>{slice&&<span className="cake-slice">🍰</span>}</button> }

function GiftBox({open,onOpen,onNavigate}) { return <main className="page gift-page"><SparkleField active={open}/><header className="hero-copy"><p>A little something made with love</p><h1>Special Package<br/>for D3 <span>💌</span></h1><div className="title-flourish"><i/>♥<i/></div><p className="intro">A little box filled with memories,<br/>love, chaos, friendship and 21 years of you.</p></header><section className={`gift-stage ${open?'opened':''}`}><div className="box-shadow"/><button className="gift-lid" onClick={onOpen} aria-label="Open the gift box"><span className="lid-ribbon"/><span className="lid-bow"><i/><b/><em>✿</em></span></button><div className="box-base"><div className="box-depth"/><div className="shred"/><div className="objects"><Envelope onClick={()=>onNavigate('letters')}/><Bouquet onClick={()=>onNavigate('flowers')}/><CameraObject onClick={()=>onNavigate('memories')}/><MiniCake onClick={()=>onNavigate('cake')}/></div></div></section><p className="instruction">{open?'Click on any treasure to open your surprise ✨':'Click the box to open your surprise ✨'}</p>{open&&<p className="object-hint">The objects are your navigation — choose one 💕</p>}</main> }

function Back({goHome}) {return <button className="back" onClick={goHome}><ArrowLeft size={17}/> Back to gift</button>}
function Flowers({goHome}) { return <main className="page checked"><Back goHome={goHome}/><SparkleField/><section className="section-head"><p>A bouquet just for you</p><h1>Flowers For You 🌷</h1><span>Because every birthday girl<br/>deserves flowers.</span></section><div className="cat-scene"><div className="cat"><span className="ears">▲　▲</span><span className="cat-face">= ᵔᴥᵔ =</span><span className="cat-bow">🎀</span><span className="paws">♢　♢</span></div><Bouquet hero/></div><p className="footer-note">For the prettiest girl ever 💗</p></main> }
function Letters({goHome}) { const [letter,setLetter]=useState(null); return <main className="page"><Back goHome={goHome}/><section className="section-head"><p>Words from my heart</p><h1>Choose a Letter ❤️</h1><span>Tap an envelope to read it</span></section><div className="letter-list">{content.letters.map((l,i)=><div className="letter-choice" key={l.title}><Envelope onClick={()=>setLetter(i)}/><span>Letter {i+1}</span></div>)}</div>{letter!==null&&<div className="modal" onClick={()=>setLetter(null)}><article className="parchment" onClick={e=>e.stopPropagation()}><button onClick={()=>setLetter(null)}>×</button><small>LETTER {letter+1}</small><h2>{content.letters[letter].title}</h2>{content.letters[letter].body.map(p=><p key={p}>{p}</p>)}<div className="pressed-flower">❀</div></article></div>}</main> }
function Memories({goHome}) { return <main className="page memories-page"><Back goHome={goHome}/><section className="section-head"><p>Every picture holds</p><h1>Our Little Memories 📸</h1><span>a little piece of us. 💕</span></section><div className="clothesline"/><div className="polaroids">{content.memories.map((m,i)=><figure key={i} className={`polaroid p${i} ${m.type}`}><span className="peg"/>{m.src?(m.type==='image'?<img src={m.src} alt={m.caption}/>:<video src={m.src} controls playsInline/>):(m.type==='image'?<div className="placeholder"><CameraIcon/></div>:<div className="placeholder video"><Play fill="white"/></div>)}<figcaption>{m.caption}</figcaption></figure>)}</div><p className="footer-note">Photos & videos are editable in <code>src/content/content.json</code></p></main> }

const cakeCopy=[['Make A Wish ✨','Close your eyes and make it count.'],['Wish Fulfilled 🌙','Ready to send it into the universe?'],['3... 2... 1...','Blow out the candles!'],['Cut Cake 🎂','Drag the knife through the cake.'],['Click The Cake Slice 💕','There is a little surprise behind it.']];
function Cake({goHome}) { const [step,setStep]=useState(0); const [drag,setDrag]=useState(0); const [done,setDone]=useState(false); const start=useRef(0); useEffect(()=>{if(step===2){const t=setTimeout(()=>setStep(3),3100);return()=>clearTimeout(t)}},[step]); const next=()=>setStep(s=>Math.min(4,s+1)); const down=e=>{if(step===3)start.current=e.clientX||e.touches?.[0].clientX}; const move=e=>{if(step!==3||!start.current)return;const x=e.clientX||e.touches?.[0].clientX;setDrag(Math.max(0,Math.min(150,x-start.current)));if(x-start.current>110){start.current=0;setStep(4)}}; return <main className="page cake-page" onPointerMove={move} onPointerUp={()=>start.current=0}><Back goHome={goHome}/><SparkleField/><section className="section-head cake-title"><p>Twenty-one wishes for you</p><h1>{cakeCopy[step][0]}</h1><span>{cakeCopy[step][1]}</span></section><div className="cake-scene"><MiniCake flames={step<2} smoke={step===2} cut={step>=3} slice={step===4} onClick={()=>step===4&&setDone(true)}/>{step===3&&<div className="knife" style={{transform:`translateX(${drag}px) rotate(-13deg)`}} onPointerDown={down}><span>♢♢♢</span></div>}{step===2&&<div className="countdown">3<br/><small>2</small><br/><b>1</b></div>}{step===4&&<div className="hidden-note">YAYYY!<br/>happy birthday<br/>gorgeous<br/>you are finally<br/>21!!!</div>}</div>{step<2&&<button className="pill" onClick={next}>{step===0?'Done Wishing ❤️':'Blow Candles'}</button>}{step===3&&<p className="drag-note">Drag the knife to cut the cake →</p>}{done&&<div className="modal confetti"><SparkleField/><article className="final-card"><button onClick={()=>setDone(false)}>×</button><h1>Yayyy!!! 🎉</h1><p>Happy Birthday Gorgeous ❤️</p><strong>You Are Finally 21!!!!</strong><div>💗 ✨ 🎂 ✨ 💗</div><button className="pill" onClick={goHome}>Continue 🌟</button></article></div>}</main> }

function App(){const [page,setPage]=useState('home');const [open,setOpen]=useState(false);const goHome=()=>{setPage('home');setOpen(true)};return <div className="app">{page==='home'&&<GiftBox open={open} onOpen={()=>setOpen(true)} onNavigate={setPage}/>} {page==='flowers'&&<Flowers goHome={goHome}/>} {page==='letters'&&<Letters goHome={goHome}/>} {page==='memories'&&<Memories goHome={goHome}/>} {page==='cake'&&<Cake goHome={goHome}/>}</div>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
